-- commented options are defaults
require('lspkind').init({
  with_text = true,
  symbol_map = {
    Class = 'פּ',
    Color = '',
    Constant = '',
    Constructor = '',
    Enum = '練',
    EnumMember = '',
    File = '',
    Folder = '',
    Function = '',
    Interface = 'ﰮ',
    Keyword = '',
    Method = '',
    Module = '',
    Property = '',
    Snippet = '﬌',
    Struct = '',
    Text = '',
    Unit = '',
    Value = '',
    Variable = '[]',
  },
})
